#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TSE-ASR End-to-End Training Script (supports single-GPU and multi-GPU DDP)

Training workflow: audio -> TSE model -> Loss backpropagation to optimize TSE

Supported loss_mode (specified in YAML config via loss_mode):
  - ce         : ASR transcription CE Loss only (Whisper teacher-forcing)
  - similarity : Speaker similarity Ranking Loss only
                 Requires sim(tse_out, enroll) > sim(mix, enroll) + margin
  - combined   : Weighted sum of CE Loss + similarity Ranking Loss + target speaker VAD Loss
                 total = lambda_ce * ce_loss + lambda_sim * sim_loss + lambda_vad * vad_loss

Key config fields (YAML):
  loss_mode   : "ce" | "similarity" | "combined"   (default "combined")
  lambda_ce   : CE loss weight                      (default 1.0)
  lambda_sim  : Similarity loss weight              (default 0.5)
  lambda_vad  : Target speaker VAD loss weight      (default 0.5)
  sim_margin  : ranking margin                      (default 0.2)
  vad_frame_shift_ms : VAD frame shift (ms)         (default 10)
  spk_encoders : language -> speaker encoder dir, e.g. {en: ..., zh: ..., th: ...}
                 (required for similarity/combined; legacy spk_encoder_en_path /
                 spk_encoder_chs_path still work)

Single GPU:
    python train.py --config configs/config_bsrnn_ecapa_vox1.yaml
Multi-GPU (torchrun):
    torchrun --nproc_per_node=4 train.py --config configs/config_bsrnn_ecapa_vox1.yaml
"""

import argparse
import json
import os
import sys
import logging
import random
import shutil
import time
import datetime
import shlex
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributed as dist
import torchaudio
import yaml
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.distributed import DistributedSampler
from torch.utils.tensorboard import SummaryWriter
from tqdm import tqdm

from resume_utils import resolve_resume_epoch

# ── wesep TSE model path ────────────────────────────────────────────────────
# Add wesep_ps4 (wesep + wespeaker) to sys.path
_SCRIPT_DIR = Path(__file__).resolve().parent
_WESEP_PATH = _SCRIPT_DIR / "wesep_ps4" / "wesep_real_tse"
_WESPEAKER_PATH = _SCRIPT_DIR / "wesep_ps4" / "wespeaker"
for _p in [_WESEP_PATH, _WESPEAKER_PATH]:
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

# Note: Whisper ASR is loaded via HuggingFace transformers, no need to inject openai-whisper path

# ===========================================================================
# Differentiable DNSMOS Loss (self-contained, loads pre-converted .pt models via torch.load)
# No dependency on onnx2torch / wesep / numba, only requires torch + torchaudio + librosa
# ===========================================================================

def _poly1d_torch(coefficients, x: torch.Tensor) -> torch.Tensor:
    result = torch.zeros_like(x)
    for c in coefficients:
        result = result * x + c
    return result


def _dnsmos_polyfit(sig: torch.Tensor, bak: torch.Tensor, ovr: torch.Tensor):
    """Mirror dnsmos_local._get_polyfit_val (non-personalized)"""
    sig_out = _poly1d_torch([-0.08397278, 1.22083953,  0.0052439],   sig)
    bak_out = _poly1d_torch([-0.13166888, 1.60915514, -0.39604546],  bak)
    ovr_out = _poly1d_torch([-0.06766283, 1.11546468,  0.04602535],  ovr)
    return sig_out, bak_out, ovr_out


class DNSMOSLoss(nn.Module):
    """Differentiable DNSMOS Loss — loads pre-converted .pt models directly, no onnx2torch/wesep/numba dependency.

    Usage:
        loss_fn = DNSMOSLoss(primary_pt, p808_pt, target_metric="OVRL")
        loss = loss_fn(inf=tse_out).mean()   # ref is optional, not used in computation

    .pt files are generated by DNSMOS/convert_onnx_to_pt.py.
    """

    _SR = 16000
    _INPUT_LEN = 9.01  # Consistent with Microsoft DNS-Challenge (seconds)

    def __init__(
        self,
        primary_model_path: str,
        p808_model_path: str,
        target_metric: str = "OVRL",
    ):
        super().__init__()
        assert target_metric in ("OVRL", "SIG", "BAK", "P808"), (
            f"target_metric must be OVRL/SIG/BAK/P808, got {target_metric!r}"
        )
        self.target_metric = target_metric
        self._len_samples = int(self._INPUT_LEN * self._SR)

        # Load the pre-converted PyTorch / TorchScript model (full model object)
        self.primary_model = torch.load(primary_model_path, weights_only=False)
        self.primary_model.eval()
        self.p808_model = torch.load(p808_model_path, weights_only=False)
        self.p808_model.eval()

        self._spectrogram = torchaudio.transforms.Spectrogram(
            n_fft=321, hop_length=160, pad_mode="constant"
        )
        self._to_db = torchaudio.transforms.AmplitudeToDB("power", top_db=80.0)

    def _melspec(self, audio: torch.Tensor) -> torch.Tensor:
        """audio: (T,) → mel (T', 120)"""
        import librosa
        import math
        fb = torch.as_tensor(
            librosa.filters.mel(sr=self._SR, n_fft=321, n_mels=120).T,
            dtype=audio.dtype, device=audio.device,
        )
        spec = self._spectrogram.to(audio.device)(audio.unsqueeze(0)).squeeze(0)  # (161, T')
        mel = torch.matmul(spec.transpose(0, 1), fb)                               # (T', 120)
        self._to_db.db_multiplier = math.log10(
            max(self._to_db.amin, float(mel.max()))
        )
        mel_db = (self._to_db(mel.transpose(0, 1)).transpose(0, 1) + 40.0) / 40.0
        return mel_db

    def _score_one(self, audio: torch.Tensor) -> torch.Tensor:
        """audio: (T,) → scalar DNSMOS score (differentiable)"""
        import math
        # Repeat-pad short audio to at least 9.01 s
        while audio.shape[0] < self._len_samples:
            audio = torch.cat([audio, audio], dim=0)

        num_hops = int(math.floor(audio.shape[0] / self._SR) - self._INPUT_LEN) + 1
        hop = self._SR
        scores: List[torch.Tensor] = []

        pm = self.primary_model.to(audio.device)
        p8 = self.p808_model.to(audio.device)

        for idx in range(num_hops):
            seg = audio[int(idx * hop): int((idx + self._INPUT_LEN) * hop)]
            if seg.shape[0] < self._len_samples:
                continue
            inp = seg.float().unsqueeze(0)              # (1, T)
            raw = pm(inp)[0]
            if raw.dim() == 2:
                raw = raw[0]
            sig_r, bak_r, ovr_r = raw[0], raw[1], raw[2]
            sig, bak, ovr = _dnsmos_polyfit(sig_r, bak_r, ovr_r)

            if self.target_metric == "P808":
                mel = self._melspec(seg[:-160])
                p808_score = p8(mel.float().unsqueeze(0))
                if p808_score.dim() > 1:
                    p808_score = p808_score.squeeze()
                scores.append(p808_score)
            else:
                scores.append({"SIG": sig, "BAK": bak, "OVRL": ovr}[self.target_metric])

        if not scores:
            return torch.zeros(1, device=audio.device, requires_grad=True).squeeze()
        return torch.stack(scores).mean()

    def forward(self, inf: torch.Tensor, ref: Optional[torch.Tensor] = None) -> torch.Tensor:
        """
        inf: (B, T)  TSE output (ref is not used and may be omitted)
        Returns: (B,) negative DNSMOS score (minimize = maximize DNSMOS)
        """
        if inf.dim() == 3:
            inf = inf[:, 0, :]
        losses: List[torch.Tensor] = []
        for i in range(inf.shape[0]):
            losses.append(-self._score_one(inf[i]))
        return torch.stack(losses)


_DNSMOS_LOSS_AVAILABLE = True   # self-contained implementation, no external dependencies


# ===========================================================================
# Dataset
# ===========================================================================

# Built-in datasets: name -> (data config key holding its subdirectory, language).
# Any other dataset can be listed in data.datasets; its subdirectory defaults to
# its name (override via data.dataset_subdirs) and its language comes from the
# meta CSV "language" column or data.dataset_langs.
# Every dataset uses TRAIN/<name>_meta.csv and TRAIN/target_activity_segments.jsonl.
BUILTIN_DATASETS: Dict[str, Tuple[str, str]] = {
    "CHiME6":     ("chime6_subdir",     "en"),
    "AMI":        ("ami_subdir",        "en"),
    "DipCo":      ("dipco_subdir",      "en"),
    "AliMeeting": ("alimeeting_subdir", "zh"),
    "AISHELL-4":  ("aishell4_subdir",   "zh"),
}

# Language codes follow Whisper (en / zh / th ...); map common aliases onto them.
LANG_ALIASES: Dict[str, str] = {"chs": "zh", "cn": "zh", "cmn": "zh", "tha": "th", "eng": "en"}


def normalize_lang(lang) -> Optional[str]:
    if lang is None or (isinstance(lang, float) and pd.isna(lang)):
        return None
    lang = str(lang).strip().lower()
    if not lang:
        return None
    return LANG_ALIASES.get(lang, lang)


def dataset_subdir(ds_name: str, data_cfg: Dict) -> str:
    """Subdirectory of a dataset relative to each train root."""
    builtin = BUILTIN_DATASETS.get(ds_name)
    if builtin is not None and data_cfg.get(builtin[0]):
        return data_cfg[builtin[0]]
    return (data_cfg.get("dataset_subdirs") or {}).get(ds_name, ds_name)


def dataset_lang(ds_name: str, data_cfg: Dict) -> Optional[str]:
    """Dataset-level language: data.dataset_langs overrides the built-in value."""
    configured = (data_cfg.get("dataset_langs") or {}).get(ds_name)
    if configured is not None:
        return normalize_lang(configured)
    builtin = BUILTIN_DATASETS.get(ds_name)
    return builtin[1] if builtin is not None else None


def _peak_normalize(wav: torch.Tensor) -> torch.Tensor:
    peak = wav.abs().max()
    return wav / peak if peak > 0 else wav


class TSEASRDataset(Dataset):
    """
    TSE-ASR training dataset

    Each sample contains:
        - mixture_wav:  multi-speaker mixture, Tensor [T]
        - enroll_wav:   target speaker enrollment audio, Tensor [T_e]
        - transcript:   target speaker transcript, str
        - language:     audio language code, e.g. 'zh' / 'en' / 'th'

    Data source: each dataset directory contains:
        - mapping.csv:   utterance -> wav path
      - TRAIN/*_meta.csv: mixture_utterance, enrolment_speakers_utterance, transcript

    Multiple data roots can be given via train_roots (e.g. original + augmented data);
    every root uses the same datasets / dataset_subdirs config and the data is merged.
    A single root (e.g. only augmented data) also works.
    """

    def __init__(
        self,
        train_roots: List[str],
        datasets: List[str],
        dataset_subdirs: Dict[str, str],
        sample_rate: int = 16000,
        max_mix_len: int = 480000,
        max_enroll_len: int = 160000,
        min_transcript_len: int = 2,
        max_samples: int = 0,
        load_vad_labels: bool = True,
        peak_normalize: bool = True,
    ):
        super().__init__()
        self.sample_rate = sample_rate
        self.peak_normalize = peak_normalize
        self.max_mix_len = max_mix_len
        self.max_enroll_len = max_enroll_len
        self.min_transcript_len = min_transcript_len
        self.load_vad_labels = load_vad_labels

        self.samples = []  # List of (mix_path, enroll_path, transcript, language, vad_segments)
        for root in train_roots:
            before = len(self.samples)
            self._load_data(root, datasets, dataset_subdirs)
            added = len(self.samples) - before
            logging.info(f"[Dataset] data root {root}: added {added} samples")

        if max_samples > 0:
            self.samples = self.samples[:max_samples]

        logging.info(f"[Dataset] loaded {len(self.samples)} samples in total")

    def _load_vad_index(
        self,
        train_root: str,
        datasets: List[str],
        dataset_subdirs: Dict[str, str],
    ) -> Dict[str, List[List[float]]]:
        """
        Load target_activity_segments.jsonl of every dataset and build a
        (mixture_utterance, speaker) -> segments index.
        """
        vad_index: Dict[Tuple[str, str], List[List[float]]] = {}
        for ds_name in datasets:
            subdir = dataset_subdir(ds_name, dataset_subdirs)
            vad_file = Path(train_root) / subdir / "TRAIN" / "target_activity_segments.jsonl"
            if not vad_file.exists():
                logging.warning(f"[Dataset] VAD label file not found: {vad_file}")
                continue
            cnt = 0
            with open(vad_file, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    rec = json.loads(line)
                    key = (rec["mixture_utterance"], rec["speaker"])
                    vad_index[key] = rec["segments"]
                    cnt += 1
            logging.info(f"[Dataset] VAD labels: {ds_name} loaded {cnt}")
        return vad_index

    def _load_data(
        self,
        train_root: str,
        datasets: List[str],
        dataset_subdirs: Dict[str, str],
    ):
        """Load samples from each dataset's mapping.csv + meta.csv"""

        # Load the VAD label index
        vad_index: Dict[Tuple[str, str], List[List[float]]] = {}
        if self.load_vad_labels:
            vad_index = self._load_vad_index(train_root, datasets, dataset_subdirs)

        for ds_name in datasets:
            subdir = dataset_subdir(ds_name, dataset_subdirs)
            ds_root = Path(train_root) / subdir

            mapping_csv = ds_root / "mapping.csv"
            meta_csv    = ds_root / "TRAIN" / f"{ds_name}_meta.csv"

            if not mapping_csv.exists():
                logging.warning(f"[Dataset] mapping.csv not found: {mapping_csv}, skipping")
                continue
            if not meta_csv.exists():
                logging.warning(f"[Dataset] meta CSV not found: {meta_csv}, skipping")
                continue

            # Load the path mapping (mixture audio only)
            mapping_df = pd.read_csv(mapping_csv)
            utterance_map: Dict[str, str] = (
                mapping_df.set_index("utterance")["path"].to_dict()
            )

            # Enrollment audio directory: enrolment_speakers/{utterance}.wav
            enroll_dir = ds_root / "enrolment_speakers"
            mix_dir    = ds_root / "mixtures"
            path_cache: Dict[Tuple[str, Path], Optional[str]] = {}

            def local_wav(utt: str, fallback_dir: Path) -> Optional[str]:
                """
                Resolve an utterance to a wav that exists on this machine, or None.
                mapping.csv may hold absolute paths from another machine (e.g. the
                published REAL-PS4 data), so fall back to <fallback_dir>/<file name>.
                Rows whose audio is missing are skipped, which also allows training
                on a partial download.
                """
                key = (utt, fallback_dir)
                if key not in path_cache:
                    mapped = utterance_map.get(utt)
                    name = os.path.basename(mapped) if mapped is not None else f"{utt}.wav"
                    found = None
                    for cand in ([mapped] if mapped is not None else []) + [str(fallback_dir / name)]:
                        if os.path.exists(cand):
                            found = cand
                            break
                    path_cache[key] = found
                return path_cache[key]

            # Load meta
            meta_df = pd.read_csv(meta_csv)

            # Per-row "language" column wins; the dataset-level language is the fallback
            ds_lang = dataset_lang(ds_name, dataset_subdirs)
            has_lang_col = "language" in meta_df.columns
            if ds_lang is None and not has_lang_col:
                logging.warning(
                    f"[Dataset] {ds_name}: no language known (add a 'language' column to "
                    f"the meta CSV or set data.dataset_langs.{ds_name}), skipping dataset"
                )
                continue
            cnt_ok = cnt_skip = cnt_missing = 0
            for _, row in meta_df.iterrows():
                mix_utt    = row["mixture_utterance"]
                enroll_utt = row["enrolment_speakers_utterance"]
                speaker    = row.get("speaker", "")
                # The column may be named "transcript" or "ground_truth_transcript"
                raw_text = row.get("transcript", row.get("ground_truth_transcript", ""))
                # pandas reads empty cells as NaN; str(NaN) == "nan" would pass the length filter
                transcript = "" if pd.isna(raw_text) else str(raw_text).strip()

                # Filter out short transcripts
                if len(transcript) < self.min_transcript_len:
                    cnt_skip += 1
                    continue

                mix_path = local_wav(mix_utt, mix_dir)

                # Enrollment audio: look up mapping.csv first, else <enrolment_speakers>/<utt>.wav
                enroll_path = local_wav(enroll_utt, enroll_dir)

                if mix_path is None or enroll_path is None:
                    cnt_missing += 1
                    continue

                # VAD segments (may be None; the VAD loss then skips this sample)
                vad_segments = vad_index.get((mix_utt, speaker), None)

                lang = (normalize_lang(row["language"]) if has_lang_col else None) or ds_lang
                if lang is None:
                    cnt_skip += 1
                    continue

                self.samples.append((mix_path, enroll_path, transcript, lang, vad_segments))
                cnt_ok += 1

            logging.info(
                f"[Dataset] {ds_name}: loaded {cnt_ok}, skipped {cnt_skip}, "
                f"missing audio {cnt_missing}"
            )

    def __len__(self) -> int:
        return len(self.samples)

    def languages(self) -> List[str]:
        return sorted({s[3] for s in self.samples})

    def __getitem__(self, idx: int) -> Optional[Dict]:
        mix_path, enroll_path, transcript, language, vad_segments = self.samples[idx]

        try:
            mix_wav,    sr_m = torchaudio.load(mix_path)
            enroll_wav, sr_e = torchaudio.load(enroll_path)
        except Exception as e:
            logging.warning(f"[Dataset] failed to load audio idx={idx}: {e}")
            return None

        # Resample
        if sr_m != self.sample_rate:
            mix_wav = torchaudio.functional.resample(mix_wav, sr_m, self.sample_rate)
        if sr_e != self.sample_rate:
            enroll_wav = torchaudio.functional.resample(enroll_wav, sr_e, self.sample_rate)

        # Downmix to mono
        if mix_wav.shape[0] > 1:
            mix_wav = mix_wav.mean(0, keepdim=True)
        if enroll_wav.shape[0] > 1:
            enroll_wav = enroll_wav.mean(0, keepdim=True)

        mix_wav    = mix_wav.squeeze(0)      # [T]
        enroll_wav = enroll_wav.squeeze(0)   # [T_e]

        # Peak-normalize to [-1, 1], same as inference.py's load_audio, so the
        # level-sensitive losses (VAD, DNSMOS) see the levels used at inference.
        if self.peak_normalize:
            mix_wav    = _peak_normalize(mix_wav)
            enroll_wav = _peak_normalize(enroll_wav)

        # Drop over-long mixtures
        if self.max_mix_len > 0 and mix_wav.shape[0] > self.max_mix_len:
            return None

        # Truncate over-long enrollments
        if self.max_enroll_len > 0 and enroll_wav.shape[0] > self.max_enroll_len:
            enroll_wav = enroll_wav[: self.max_enroll_len]

        return {
            "mixture":      mix_wav,        # [T]
            "enroll":       enroll_wav,     # [T_e]
            "transcript":   transcript,     # str
            "language":     language,       # language code, e.g. 'zh' / 'en' / 'th'
            "vad_segments": vad_segments,   # List[[start, end]] or None
        }


def tse_asr_collate_fn(batch: List) -> Optional[Dict]:
    """
    Pad and assemble a batch, dropping None samples.
    Returns:
        mixture:  [B, T_max]  (zero-padded)
        enroll:   [B, T_e_max]
            mix_lens: [B]  real lengths (samples)
        transcripts: List[str]
            languages:   List[str]  language of each sample
            vad_segments: List[Optional[List[[start, end]]]]  target speaker VAD labels
    """
    batch = [b for b in batch if b is not None]
    if len(batch) == 0:
        return None

    mix_wavs      = [b["mixture"]    for b in batch]
    enroll_wavs   = [b["enroll"]     for b in batch]
    transcripts   = [b["transcript"] for b in batch]
    languages     = [b["language"] for b in batch]   # every sample must have a language field
    vad_segments  = [b.get("vad_segments", None) for b in batch]

    mix_lens    = torch.tensor([w.shape[0] for w in mix_wavs], dtype=torch.long)
    enroll_lens = torch.tensor([w.shape[0] for w in enroll_wavs], dtype=torch.long)

    mixture = torch.nn.utils.rnn.pad_sequence(mix_wavs,    batch_first=True)
    enroll  = torch.nn.utils.rnn.pad_sequence(enroll_wavs, batch_first=True)

    return {
        "mixture":      mixture,       # [B, T_max]
        "enroll":       enroll,        # [B, T_e_max]
        "mix_lens":     mix_lens,      # [B]
        "enroll_lens":  enroll_lens,   # [B]
        "transcripts":  transcripts,   # List[str]
        "languages":    languages,     # List[str], language of each sample
        "vad_segments": vad_segments,  # List[Optional[List[[start,end]]]]
    }


# ===========================================================================
# TSE model loading
# ===========================================================================

def build_tse_model(cfg: Dict, pretrained_path: Optional[str] = None) -> nn.Module:
    """
    Build the TSE model from the config and load pretrained weights.

    Supports:
        - BSRNN          (legacy BSRNN in bsrnn_legacy.py, via wesep's legacy path)
        - TSE_BSRNN_SPK  (newer joint model in wesep_real_tse; not bundled in wesep_ps4)
        - TFGridNet      (if available; not bundled in wesep_ps4)
    """
    from wesep.models import get_model

    model_name = cfg["model"]["tse_model"]
    model_args = dict(cfg["model_args"]["tse_model"])  # shallow copy so the original cfg is not modified

    # Resolve a relative spk_model_init path to an absolute path
    if "spk_model_init" in model_args and model_args["spk_model_init"]:
        smi = model_args["spk_model_init"]
        if not os.path.isabs(smi):
            smi_abs = str((Path(_SCRIPT_DIR) / smi).resolve())
            model_args["spk_model_init"] = smi_abs
            logging.info(f"[TSE] spk_model_init resolved to: {smi_abs}")

    model_cls = get_model(model_name)
    model = model_cls(**model_args)  # unpack the dict as keyword arguments

    if pretrained_path is not None and pretrained_path != "null":
        pretrained_path = str(Path(_SCRIPT_DIR) / pretrained_path)
        logging.info(f"[TSE] loading pretrained weights: {pretrained_path}")
        ckpt = torch.load(pretrained_path, map_location="cpu")
        # Support several checkpoint formats
        # wesep training format: {"models": [state_dict], "optimizers": [...], ...}
        if isinstance(ckpt, dict) and "models" in ckpt:
            models_val = ckpt["models"]
            if isinstance(models_val, list) and len(models_val) > 0:
                state_dict = models_val[0]
            elif isinstance(models_val, dict):
                state_dict = models_val
            else:
                state_dict = ckpt
        else:
            state_dict = ckpt.get("model", ckpt.get("state_dict", ckpt)) if isinstance(ckpt, dict) else ckpt
        missing, unexpected = model.load_state_dict(state_dict, strict=False)
        if missing:
            logging.warning(f"[TSE] missing keys ({len(missing)}): {missing[:5]}...")
        if unexpected:
            logging.warning(f"[TSE] unexpected keys ({len(unexpected)}): {unexpected[:5]}...")

    return model


# ===========================================================================
# ASR model (Whisper, frozen)
# ===========================================================================

class FrozenWhisperASR(nn.Module):
    """
    Frozen Whisper ASR model (HuggingFace transformers).
    Computes a token-level cross-entropy loss on the TSE output audio.

    Forward input:  extracted waveform (float32, 16 kHz)
    Forward output: CE loss scalar (backpropagates into the TSE model)

    Gradient path: tse_wav -> STFT -> mel filterbank -> log_mel -> encoder -> decoder -> CE loss
    """

    # Whisper constants
    N_FFT     = 400
    HOP       = 160
    N_MELS    = 128   # large-v3 uses 128 mel bins
    MAX_FRAME = 3000  # 30s at 10ms shift，16kHz
    SAMPLE_RATE = 16000

    def __init__(self, model_path: str, device: str = "cuda"):
        super().__init__()
        from transformers import WhisperForConditionalGeneration, WhisperTokenizer, WhisperConfig

        logging.info(f"[ASR] loading Whisper model (transformers): {model_path}")
        self.hf_model = WhisperForConditionalGeneration.from_pretrained(
            model_path,
            dtype=torch.float32,
        )

        # Freeze all parameters
        for p in self.hf_model.parameters():
            p.requires_grad_(False)
        self.hf_model.eval()

        # Load the tokenizer
        self.tokenizer = WhisperTokenizer.from_pretrained(model_path)

        # Precompute the mel filterbank (fixed matrix, no gradient)
        # using torchaudio's melscale_fbanks
        mel_fb = torchaudio.functional.melscale_fbanks(
            n_freqs=self.N_FFT // 2 + 1,
            f_min=0.0,
            f_max=8000.0,
            n_mels=self.N_MELS,
            sample_rate=self.SAMPLE_RATE,
            norm="slaney",
            mel_scale="slaney",
        )  # [n_freqs, n_mels]
        self.register_buffer("mel_fb", mel_fb)  # no gradient; moves with .to(device)

        logging.info(f"[ASR] Whisper parameters frozen, mel_bins={self.N_MELS}")

    def check_languages(self, languages: List[str]):
        """Fail early if a language has no Whisper token (it would silently map to <unk>)."""
        unk = self.tokenizer.unk_token_id
        bad = [l for l in languages
               if self.tokenizer.convert_tokens_to_ids(f"<|{l}|>") in (None, unk)]
        if bad:
            raise ValueError(f"[ASR] Whisper has no language token for {bad}")

    def _compute_mel_with_grad(self, wav: torch.Tensor) -> torch.Tensor:
        """
        Differentiable log-mel spectrogram (pure PyTorch, gradients flow back).
        Matches WhisperFeatureExtractor.

        Input:  wav [T], float32, 16 kHz
        Output: log_mel [1, N_MELS, MAX_FRAME]
        """
        device = wav.device
        window = torch.hann_window(self.N_FFT, device=device)

        # Match WhisperFeatureExtractor: zero-pad the *waveform* to 30 s before the
        # STFT (padding the normalized log-mel with 0 would look like loud speech),
        # then drop the last STFT frame to get exactly MAX_FRAME frames.
        n_samples = self.MAX_FRAME * self.HOP
        if wav.shape[0] < n_samples:
            wav = F.pad(wav, (0, n_samples - wav.shape[0]))
        else:
            wav = wav[:n_samples]

        stft = torch.stft(
            wav,
            n_fft=self.N_FFT,
            hop_length=self.HOP,
            window=window,
            return_complex=True,
        )  # [F, MAX_FRAME + 1]，F = N_FFT/2+1

        magnitudes = stft[..., :-1].abs() ** 2  # power spectrum [F, MAX_FRAME]

        # mel_fb: [F, N_MELS]，magnitudes: [F, T_stft]
        mel_spec = self.mel_fb.T @ magnitudes   # [N_MELS, T_stft]

        # Log compression (same as WhisperFeatureExtractor: log10 + normalization)
        log_mel = (mel_spec.clamp(min=1e-10)).log10()
        log_mel = torch.maximum(log_mel, log_mel.max() - 8.0)
        log_mel = (log_mel + 4.0) / 4.0

        return log_mel.unsqueeze(0)  # [1, N_MELS, MAX_FRAME]

    def forward(
        self,
        audio: torch.Tensor,                    # [B, T]，float32，16kHz
        transcripts: List[str],
        language: Optional[str] = None,         # global default language (None = use per-sample languages)
        languages: Optional[List[str]] = None,  # per-sample languages (takes precedence over language)
    ) -> torch.Tensor:
        """
        Teacher-forcing CE loss。

        Args:
                audio:       mono TSE output audio [B, T]
                transcripts: target transcripts, length B
                language:    global language code, used when languages is None
                languages:   per-sample language codes (takes precedence; handles mixed-language batches)

        Returns:
                loss: scalar Tensor (CE loss, backpropagates into the TSE model)
        """
        if audio.dim() == 1:
            audio = audio.unsqueeze(0)
        B = audio.shape[0]

        # Language of each sample
        if languages is not None and len(languages) == B:
            per_sample_lang = languages
        elif language is not None:
            per_sample_lang = [language] * B
        else:
            per_sample_lang = ["zh"] * B  # fallback default

        sot_id = self.tokenizer.convert_tokens_to_ids("<|startoftranscript|>")
        eot_id = self.tokenizer.eos_token_id
        task_token  = "<|transcribe|>"
        notimestamp = "<|notimestamps|>"

        total_loss  = torch.tensor(0.0, device=audio.device, requires_grad=True)
        valid_count = 0

        for i in range(B):
            wav = audio[i]  # [T]

            # ── Per-sample language token ─────────────────────────────────────────
            lang_i = per_sample_lang[i]
            lang_token = f"<|{lang_i}|>"
            forced_prefix_ids = self.tokenizer.convert_tokens_to_ids(
                [lang_token, task_token, notimestamp]
            )

            # ── Differentiable mel (gradient path) ────────────────────────────────
            mel_with_grad = self._compute_mel_with_grad(wav)  # [1, N_MELS, MAX_FRAME]

            # ── Encoder forward (keeps the gradient path) ─────────────────────────
            enc_out = self.hf_model.model.encoder(
                input_features=mel_with_grad
            ).last_hidden_state  # [1, T_enc, D]

            # ── Tokenize the target text ──────────────────────────────────────────
            text = transcripts[i]
            # Whisper emits English text with a leading space (" Hello"), so the
            # target must start with a space-prefixed token to be in-distribution.
            if lang_i == "en" and not text.startswith(" "):
                text = " " + text
            text_ids = self.tokenizer.encode(text, add_special_tokens=False)
            # Decoder input: [SOT, lang, task, notimestamp, text..., EOT]
            full_ids     = [sot_id] + forced_prefix_ids + text_ids + [eot_id]
            decoder_in   = torch.tensor(full_ids[:-1], dtype=torch.long,
                                        device=audio.device).unsqueeze(0)  # [1, L-1]
            decoder_tgt  = torch.tensor(full_ids[1:],  dtype=torch.long,
                                        device=audio.device).unsqueeze(0)  # [1, L-1]

            # ── Decoder forward（teacher-forcing）────────────────────────
            dec_out = self.hf_model.model.decoder(
                input_ids=decoder_in,
                encoder_hidden_states=enc_out,
            ).last_hidden_state  # [1, L-1, D]

            # ── Project to the vocabulary ─────────────────────────────────────────
            logits = self.hf_model.proj_out(dec_out)  # [1, L-1, V]

            logits_flat = logits.view(-1, logits.shape[-1])  # [(L-1), V]
            target_flat = decoder_tgt.view(-1)               # [(L-1)]

            loss_i = F.cross_entropy(logits_flat, target_flat, ignore_index=-100)
            total_loss  = total_loss + loss_i
            valid_count += 1

        if valid_count == 0:
            return total_loss

        return total_loss / valid_count

    def decode(
        self,
        audio: torch.Tensor,
        language: str = "zh",
    ) -> List[str]:
        """
        Inference decoding (no gradients), for logging.
        """
        from transformers import WhisperProcessor

        if audio.dim() == 1:
            audio = audio.unsqueeze(0)

        results = []
        with torch.no_grad():
            for i in range(audio.shape[0]):
                wav_np = audio[i].float().cpu().numpy()
                # Use generate() (standard HuggingFace inference)
                processor = WhisperProcessor.from_pretrained(
                    self.tokenizer.name_or_path
                    if hasattr(self.tokenizer, "name_or_path") else "openai/whisper-large-v3"
                )
                inputs = processor(
                    wav_np,
                    sampling_rate=self.SAMPLE_RATE,
                    return_tensors="pt",
                ).input_features.to(next(self.hf_model.parameters()).device)
                pred_ids = self.hf_model.generate(
                    inputs,
                    language=language,
                    task="transcribe",
                )
                text = self.tokenizer.decode(pred_ids[0], skip_special_tokens=True)
                results.append(text)
        return results


# ===========================================================================
# Speaker encoders (frozen, for the similarity loss)
# wespeaker models identical to the evaluation side (wespeakerruntime), e.g.:
#   - English datasets (CHiME6/AMI): voxceleb_resnet34_LM
#   - Chinese datasets (AliMeeting/AISHELL-4): cnceleb_resnet34_LM
# Feature extraction matches wespeakerruntime/speaker.py _compute_fbank exactly:
#   waveform * 32768 → kaldi.fbank(80mel, 25ms/10ms, hamming) → CMN(axis=0)
# ===========================================================================

class FrozenSpeakerEncoder(nn.Module):
    """
    Load a pretrained wespeaker speaker encoder and freeze all parameters.
    Feature extraction matches the evaluation side (wespeakerruntime) to avoid a train-eval mismatch.

    Forward input:  waveform [B, T], float32, 16 kHz
    Forward output: speaker embedding [B, D]

    Feature pipeline (same as wespeakerruntime/speaker.py._compute_fbank):
      wav * 32768 → kaldi.fbank(n_mels=80, frame_length=25ms, frame_shift=10ms,
                                window_type='hamming', dither=0.0)
        → CMN (subtract the per-frequency mean over time, axis=0 i.e. dim=1)
    """

    def __init__(self, model_dir: str, device: str = "cuda"):
        super().__init__()
        import yaml as _yaml
        import torchaudio.compliance.kaldi as kaldi  # noqa: F401 (check that it is available)

        model_dir = Path(model_dir)
        config_path = model_dir / "config.yaml"
        model_path  = model_dir / "avg_model.pt"

        if not config_path.exists():
            raise FileNotFoundError(f"[SpeakerEncoder] config.yaml not found: {config_path}")
        if not model_path.exists():
            raise FileNotFoundError(f"[SpeakerEncoder] avg_model.pt not found: {model_path}")

        with open(config_path, "r", encoding="utf-8") as f:
            spk_cfg = _yaml.safe_load(f)

        # wespeaker config layout: model / model_args
        spk_model_name   = spk_cfg.get("model", "ResNet34")
        spk_model_kwargs = spk_cfg.get("model_args", {})

        from wespeaker.models.speaker_model import get_speaker_model
        spk_cls = get_speaker_model(spk_model_name)
        self.encoder = spk_cls(**spk_model_kwargs)

        ckpt = torch.load(str(model_path), map_location="cpu")
        # Support several checkpoint formats
        if isinstance(ckpt, dict) and "model" in ckpt:
            state_dict = ckpt["model"]
        elif isinstance(ckpt, dict) and "state_dict" in ckpt:
            state_dict = ckpt["state_dict"]
        else:
            state_dict = ckpt

        missing, unexpected = self.encoder.load_state_dict(state_dict, strict=False)
        if missing:
            logging.warning(f"[SpeakerEncoder] missing keys ({len(missing)}): {missing[:3]}")
        if unexpected:
            logging.warning(f"[SpeakerEncoder] unexpected keys ({len(unexpected)}): {unexpected[:3]}")

        # Freeze all parameters
        for p in self.encoder.parameters():
            p.requires_grad_(False)
        self.encoder.eval()

        # fbank parameters (same as wespeakerruntime); take them from the model's own
        # training config when present (dither is always 0 for embedding extraction)
        fbank_args = (spk_cfg.get("dataset_args") or {}).get("fbank_args") or {}
        self.sample_rate   = int((spk_cfg.get("dataset_args") or {}).get("resample_rate", 16000))
        self.num_mel_bins  = int(fbank_args.get(
            "num_mel_bins",
            spk_model_kwargs.get("feat_dim", spk_model_kwargs.get("acoustic_dim", 80)),
        ))
        self.frame_length  = fbank_args.get("frame_length", 25)    # ms
        self.frame_shift   = fbank_args.get("frame_shift", 10)     # ms
        if self.sample_rate != 16000:
            raise ValueError(
                f"[SpeakerEncoder] {model_dir} expects {self.sample_rate} Hz audio; only 16 kHz is supported"
            )

        logging.info(
            f"[SpeakerEncoder] loaded and froze {spk_model_name}: {model_path}  "
            f"fbank: n_mels={self.num_mel_bins}, frame_length={self.frame_length}ms, "
            f"frame_shift={self.frame_shift}ms"
        )

    def _wav_to_fbank(self, wav: torch.Tensor) -> torch.Tensor:
        """
        Convert raw waveforms [B, T] to fbank features [B, T_frames, feat_dim].
        Matches wespeakerruntime/speaker.py._compute_fbank exactly:
            1. wav * 32768 (amplitude scaling)
            2. kaldi.fbank (hamming window, dither=0)
            3. CMN: subtract the per-frequency mean over time

        Note: kaldi.fbank has no batch support, so samples are processed one by one and stacked.
        Gradients flow through this method (kaldi.fbank is differentiable).
        """
        import torchaudio.compliance.kaldi as kaldi

        B = wav.shape[0]
        fbank_list = []
        for i in range(B):
            w = wav[i].unsqueeze(0)          # [1, T]
            w = w * (1 << 15)                # amplitude scaling x32768
            feat = kaldi.fbank(
                w,
                num_mel_bins=self.num_mel_bins,
                frame_length=self.frame_length,
                frame_shift=self.frame_shift,
                dither=0.0,
                sample_frequency=self.sample_rate,
                window_type="hamming",
                use_energy=False,
            )  # [T_frames, feat_dim]
            # CMN: subtract the per-frequency mean over time (axis=0 in numpy = dim=0 in 2D tensor)
            feat = feat - feat.mean(dim=0, keepdim=True)  # [T_frames, feat_dim]
            fbank_list.append(feat)

        # Pad to the same length, then stack
        max_len = max(f.shape[0] for f in fbank_list)
        padded = []
        for f in fbank_list:
            if f.shape[0] < max_len:
                pad = torch.zeros(max_len - f.shape[0], f.shape[1],
                                  dtype=f.dtype, device=f.device)
                f = torch.cat([f, pad], dim=0)
            padded.append(f)
        return torch.stack(padded, dim=0)  # [B, T_frames, feat_dim]

    def forward(self, wav: torch.Tensor) -> torch.Tensor:
        """
        Input:  [B, T] or [T], float32, 16 kHz raw waveform
        Output: [B, D] speaker embedding
        """
        if wav.dim() == 1:
            wav = wav.unsqueeze(0)
        fbank = self._wav_to_fbank(wav)          # [B, T_frames, feat_dim]
        with torch.no_grad():
            emb = self.encoder(fbank)
        # Speaker models return (frame_feats, embedding) or just the embedding
        if isinstance(emb, (tuple, list)):
            emb = emb[-1]
        return emb  # [B, D]


# ===========================================================================
# Speaker similarity ranking loss (optional)
# One frozen speaker encoder per language (e.g. en / zh / th); each sample uses
# the encoder of its own language, which should match the evaluation side.
# ===========================================================================

class SpeakerSimilarityLoss(nn.Module):
    """
    Hinge ranking loss：
        requires cos-sim(TSE output, enrollment) > cos-sim(mixture, enrollment) + margin
      loss = mean( max(0, margin - (sim(tse, enroll) - sim(mix, enroll))) )

    encoders maps a language code to its encoder; samples are routed by the
    languages list. Gradients only flow through tse_wav.
    """

    def __init__(
        self,
        encoders: Dict[str, FrozenSpeakerEncoder],
        margin: float = 0.2,
    ):
        super().__init__()
        if not encoders:
            raise ValueError("[SpeakerSimilarityLoss] at least one speaker encoder is required")
        self.encoders = nn.ModuleDict(encoders)
        self.margin   = margin

    def _get_encoder(self, lang: str) -> FrozenSpeakerEncoder:
        key = normalize_lang(lang)
        if key not in self.encoders:
            # No silent fallback: a wrong-language encoder gives misleading similarities
            raise KeyError(
                f"no speaker encoder for language {lang!r}; configured: {sorted(self.encoders)}"
            )
        return self.encoders[key]

    def forward(
        self,
        tse_wav:    torch.Tensor,    # [B, T_tse]
        mix_wav:    torch.Tensor,    # [B, T_mix]
        enroll_wav: torch.Tensor,    # [B, T_e]
        languages:  List[str],       # language of each sample, length B
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Returns: (loss, sim_tse_enroll_mean, sim_mix_enroll_mean)
            - loss: scalar, backpropagates
            - sim_tse_enroll_mean / sim_mix_enroll_mean: detached scalars for logging
        """
        B = tse_wav.shape[0]
        emb_tse_list    = []
        emb_enroll_list = []
        emb_mix_list    = []

        for i in range(B):
            enc = self._get_encoder(languages[i])

            # Enrollment & mixture embeddings: frozen, no gradient
            with torch.no_grad():
                e_enroll = enc(enroll_wav[i:i+1])   # [1, D]
                e_mix    = enc(mix_wav[i:i+1])       # [1, D]
                e_enroll = F.normalize(e_enroll, dim=-1)
                e_mix    = F.normalize(e_mix,    dim=-1)

            # TSE embedding needs gradients (tse_wav -> fbank -> encoder)
            # The encoder is frozen, but gradients w.r.t. the audio flow through _wav_to_fbank and the encoder
            fbank_tse = enc._wav_to_fbank(tse_wav[i:i+1])   # [1, T_frames, feat_dim]
            e_tse = enc.encoder(fbank_tse)
            if isinstance(e_tse, (tuple, list)):
                e_tse = e_tse[-1]
            e_tse = F.normalize(e_tse, dim=-1)               # [1, D]

            emb_tse_list.append(e_tse)
            emb_enroll_list.append(e_enroll)
            emb_mix_list.append(e_mix)

        emb_tse    = torch.cat(emb_tse_list,    dim=0)  # [B, D]
        emb_enroll = torch.cat(emb_enroll_list, dim=0)  # [B, D]
        emb_mix    = torch.cat(emb_mix_list,    dim=0)  # [B, D]

        sim_tse_enroll = (emb_tse * emb_enroll).sum(dim=-1)  # [B]
        sim_mix_enroll = (emb_mix * emb_enroll).sum(dim=-1)  # [B]

        loss = F.relu(self.margin - (sim_tse_enroll - sim_mix_enroll)).mean()

        return loss, sim_tse_enroll.detach().mean(), sim_mix_enroll.detach().mean()


# ===========================================================================
# Target speaker activity loss (target VAD loss)
# ===========================================================================

class TargetVADLoss(nn.Module):
    """
    Target speaker voice activity loss.

    The TSE output should be near-silent on frames where the target speaker is
    inactive and clearly audible where the target speaker is active.

    Frame levels are measured in dB relative to the loudest frame of the
    *mixture* (not as absolute energy), so the loss does not depend on the
    recording level and gives no incentive to simply amplify the output:
      rel_db = 10 * log10(P_tse_frame / max(P_mix_frame))
      logit  = (rel_db - threshold_db) / slope_db
      loss   = BCE_with_logits(logit, frame_label)

    With the defaults (threshold -40 dB, slope 5 dB): -20 dB -> p=0.98,
    -40 dB -> p=0.5, -60 dB -> p=0.02. Levels are floored at floor_db.

    Gradient path: tse_wav -> frame power -> rel_db -> BCE loss
    """

    def __init__(
        self,
        sample_rate: int = 16000,
        frame_shift_ms: float = 10.0,
        frame_length_ms: float = 25.0,
        threshold_db: float = -40.0,
        slope_db: float = 5.0,
        floor_db: float = -80.0,
        energy_floor: float = 1e-10,
    ):
        super().__init__()
        self.sample_rate = sample_rate
        self.frame_shift = int(sample_rate * frame_shift_ms / 1000.0)
        self.frame_length = int(sample_rate * frame_length_ms / 1000.0)
        self.threshold_db = threshold_db
        self.slope_db = slope_db
        self.floor_db = floor_db
        self.energy_floor = energy_floor

    def _frame_power(self, wav: torch.Tensor) -> torch.Tensor:
        """wav [B, T] -> mean power per frame [B, N_frames] (differentiable)"""
        frames = wav.unfold(dimension=1, size=self.frame_length, step=self.frame_shift)
        return (frames ** 2).mean(dim=-1)

    def _segments_to_frame_labels(
        self,
        segments: List[List[float]],
        num_frames: int,
        device: torch.device,
    ) -> torch.Tensor:
        """
        Convert time segments [[start1, end1], [start2, end2], ...] into per-frame 0/1 labels.

        Segment times are in seconds, relative to the mixture start.
        Output: [num_frames] float Tensor, 1.0 = speaking, 0.0 = silent
        """
        labels = torch.zeros(num_frames, device=device)
        for seg in segments:
            start_sec, end_sec = seg[0], seg[1]
            start_frame = int(start_sec * self.sample_rate / self.frame_shift)
            end_frame   = int(end_sec   * self.sample_rate / self.frame_shift)
            start_frame = max(0, min(start_frame, num_frames))
            end_frame   = max(0, min(end_frame,   num_frames))
            if start_frame < end_frame:
                labels[start_frame:end_frame] = 1.0
        return labels

    def forward(
        self,
        tse_wav: torch.Tensor,                        # [B, T]
        vad_segments: List[Optional[List[List[float]]]],  # VAD segments of each sample in the batch
        mix_lens: torch.Tensor,                       # [B] real lengths
        mix_wav: torch.Tensor,                        # [B, T] mixture (level reference)
    ) -> torch.Tensor:
        """
        Target speaker activity BCE loss.

        Args:
                tse_wav:      TSE output audio [B, T]
                vad_segments: per-sample VAD segments (None = no label, sample skipped)
                mix_lens:     per-sample real audio length (samples)
            mix_wav:      mixture [B, T]; its loudest frame is the 0 dB reference

        Returns:
                loss: scalar Tensor (backpropagates)
        """
        B = tse_wav.shape[0]
        device = tse_wav.device

        tse_power = self._frame_power(tse_wav.float())            # [B, N_frames]
        with torch.no_grad():
            mix_power = self._frame_power(mix_wav.float())        # [B, N_frames]
        N_frames = min(tse_power.shape[1], mix_power.shape[1])

        total_loss = torch.tensor(0.0, device=device, requires_grad=True)
        valid_count = 0

        for i in range(B):
            if vad_segments[i] is None:
                continue

            # Frames that lie fully inside the real (unpadded) audio
            actual_len = int(mix_lens[i].item())
            actual_frames = min(
                (actual_len - self.frame_length) // self.frame_shift + 1,
                N_frames,
            )
            if actual_frames <= 0:
                continue

            labels = self._segments_to_frame_labels(
                vad_segments[i], actual_frames, device
            )  # [actual_frames]

            ref = mix_power[i, :actual_frames].max().clamp(min=self.energy_floor)
            rel = (tse_power[i, :actual_frames] / ref).clamp(min=10 ** (self.floor_db / 10))
            rel_db = 10.0 * torch.log10(rel)
            logits = (rel_db - self.threshold_db) / self.slope_db

            loss_i = F.binary_cross_entropy_with_logits(logits, labels, reduction="mean")
            total_loss = total_loss + loss_i
            valid_count += 1

        if valid_count == 0:
            return total_loss

        return total_loss / valid_count


# ===========================================================================
# Learning-rate scheduler
# ===========================================================================

class ExponentialDecayScheduler:
    """
    Exponential-decay LR scheduler (same as wesep).

    Linear warm-up to initial_lr over warm_up_epoch epochs (from initial_lr, or from 0),
    then exponential decay from initial_lr to final_lr.
    """

    def __init__(
        self,
        optimizer: torch.optim.Optimizer,
        initial_lr: float,
        final_lr: float,
        num_epochs: int,
        epoch_iter: int,
        warm_up_epoch: int = 1,
        warm_from_zero: bool = False,
    ):
        self.optimizer      = optimizer
        self.initial_lr     = initial_lr
        self.final_lr       = final_lr
        self.num_epochs     = num_epochs
        self.epoch_iter     = epoch_iter
        self.warm_up_epoch  = warm_up_epoch
        self.warm_from_zero = warm_from_zero
        self.total_steps    = num_epochs * epoch_iter
        self.warm_steps     = warm_up_epoch * epoch_iter
        self._step          = 0

    def step(self):
        self._step += 1
        lr = self._get_lr()
        for pg in self.optimizer.param_groups:
            pg["lr"] = lr

    def _get_lr(self) -> float:
        if self._step <= self.warm_steps and self.warm_steps > 0:
            start = 0.0 if self.warm_from_zero else self.initial_lr
            frac  = self._step / self.warm_steps
            return start + frac * (self.initial_lr - start)

        # Exponential decay phase
        decay_steps = self.total_steps - self.warm_steps
        step_in_decay = self._step - self.warm_steps
        if decay_steps <= 0:
            return self.final_lr
        frac = step_in_decay / decay_steps
        # Log-linear interpolation
        lr = self.initial_lr * (self.final_lr / self.initial_lr) ** frac
        return float(np.clip(lr, self.final_lr, self.initial_lr))

    def get_last_lr(self) -> float:
        return self._get_lr()

    def state_dict(self) -> Dict:
        return {"_step": self._step}

    def load_state_dict(self, d: Dict):
        self._step = d["_step"]


# ===========================================================================
# Checkpoint utilities
# ===========================================================================

def save_checkpoint(
    path: str,
    step: int,
    epoch: int,
    tse_model: nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler: ExponentialDecayScheduler,
    best_loss: float,
    epoch_finished: bool = False,
):
    torch.save(
        {
            "step":      step,
            "epoch":     epoch,
            "epoch_finished": epoch_finished,  # True: epoch completed, resume from epoch + 1
            "model":     tse_model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "scheduler": scheduler.state_dict(),
            "best_loss": best_loss,
        },
        path,
    )


def load_checkpoint(
    path: str,
    tse_model: nn.Module,
    optimizer: Optional[torch.optim.Optimizer] = None,
    scheduler: Optional[ExponentialDecayScheduler] = None,
) -> Tuple[int, int, float, bool]:
    """
    Returns (step, epoch, best_loss, epoch_finished)
    """
    logging.info(f"[Ckpt] resuming training from {path}")
    ckpt = torch.load(path, map_location="cpu")
    tse_model.load_state_dict(ckpt["model"])
    if optimizer is not None and "optimizer" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer"])
    if scheduler is not None and "scheduler" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler"])
    epoch_finished = ckpt.get("epoch_finished")
    if epoch_finished is None:
        # Older checkpoints lack this field: infer from the file name (epoch-end / best = finished)
        name = Path(path).resolve().name
        epoch_finished = name.startswith(("checkpoint_epoch", "best_checkpoint"))
    return (
        ckpt.get("step", 0),
        ckpt.get("epoch", 0),
        ckpt.get("best_loss", float("inf")),
        bool(epoch_finished),
    )


def rotate_checkpoints(ckpt_dir: str, max_keep: int):
    """Keep the newest max_keep checkpoint_step*.pt files and delete older ones"""
    ckpts = sorted(Path(ckpt_dir).glob("checkpoint_step*.pt"))
    if len(ckpts) > max_keep:
        for old in ckpts[: len(ckpts) - max_keep]:
            old.unlink()
            logging.debug(f"[Ckpt] deleted old checkpoint: {old.name}")


# ===========================================================================
# Training loop
# ===========================================================================

def run_tse_forward(
    tse_model: nn.Module,
    mixture: torch.Tensor,     # [B, T]
    enroll: torch.Tensor,      # [B, T_e]
) -> torch.Tensor:
    """
    Run the TSE model to extract the target speaker audio.
    Supports both the legacy wesep BSRNN and the newer TSE_BSRNN_SPK interfaces.

    Returns: tse_out [B, T] (same length as the mixture)
    """
    out = tse_model(mixture, enroll)

    # Handle different return formats
    if isinstance(out, (tuple, list)):
        tse_out = out[0]  # the first output is the separated audio
    else:
        tse_out = out

    # Make sure the shape is [B, T]
    if tse_out.dim() == 3:
        tse_out = tse_out.squeeze(1)   # [B, 1, T] -> [B, T]

    return tse_out


def train_one_epoch(
    tse_model:    nn.Module,
    asr_model:    Optional[FrozenWhisperASR],
    dataloader:   DataLoader,
    optimizer:    torch.optim.Optimizer,
    scheduler:    ExponentialDecayScheduler,
    device:       torch.device,
    epoch:        int,
    global_step:  int,
    cfg:          Dict,
    writer:       Optional[SummaryWriter],
    logger:       logging.Logger,
    spk_loss_fn:   Optional[SpeakerSimilarityLoss] = None,
    vad_loss_fn:   Optional[TargetVADLoss] = None,
    dnsmos_loss_fn = None,
    is_main:       bool = True,
    world_size:   int = 1,
) -> Tuple[float, int]:
    """
    Train one epoch. Returns (epoch_loss, global_step).
    Multi-GPU: each GPU runs its own dataloader shard; losses are all-reduced and rank 0 logs them.
    Only rank 0 (is_main=True) writes checkpoints.
    """
    tse_model.train()

    loss_mode      = cfg.get("loss_mode", "combined")
    lambda_ce      = cfg.get("lambda_ce",      1.0)
    lambda_sim     = cfg.get("lambda_sim",     0.5)
    lambda_vad     = cfg.get("lambda_vad",     0.5)
    lambda_dnsmos  = cfg.get("lambda_dnsmos",  0.0)
    # Backward compatibility with the old lambda_spk
    if cfg.get("lambda_spk", 0.0) > 0 and loss_mode == "ce":
        loss_mode  = "combined"
        lambda_sim = cfg["lambda_spk"]

    clip_grad      = cfg.get("clip_grad", 5.0)
    log_every      = cfg.get("log_every", 20)
    save_step_int  = cfg.get("save_step_interval", 500)
    max_keep_ckpts = cfg.get("max_keep_ckpts", 3)
    exp_dir        = cfg["exp_dir"]
    model_dir      = Path(exp_dir) / "models"
    asr_language   = cfg.get("asr_language", "zh")

    # Validate the loss mode
    valid_modes = ("ce", "similarity", "combined")
    if loss_mode not in valid_modes:
        raise ValueError(f"[Train] invalid loss_mode={loss_mode!r}, valid values: {valid_modes}")
    if loss_mode in ("similarity", "combined") and spk_loss_fn is None:
        raise ValueError(
            f"[Train] loss_mode={loss_mode!r} needs spk_loss_fn; "
            "set spk_encoders in the config"
        )
    if loss_mode in ("ce", "combined") and asr_model is None:
        raise ValueError(
            f"[Train] loss_mode={loss_mode!r} needs asr_model; "
            "set whisper_model_path in the config"
        )

    amp_dtype     = parse_amp_dtype(cfg.get("amp_dtype", "float32"))
    # AMP is on only when enabled AND a half-precision dtype is chosen
    enable_amp    = bool(cfg.get("enable_amp", False)) and amp_dtype is not None
    # Loss scaling is only needed for float16; bfloat16 has the float32 range
    scaler        = torch.cuda.amp.GradScaler(enabled=enable_amp and amp_dtype == torch.float16)

    # Unwrapped module (for checkpoint saving and the speaker encoder)
    raw_model = tse_model.module if hasattr(tse_model, "module") else tse_model

    running_loss   = 0.0
    running_ce     = 0.0
    running_sim    = 0.0
    running_vad    = 0.0
    running_dnsmos = 0.0
    n_batches      = 0
    # Whole-epoch totals (running_* are reset every log_every steps)
    epoch_loss_sum = 0.0
    epoch_batches  = 0
    best_loss    = cfg.get("_best_loss", float("inf"))

    # Progress bar on rank 0 only
    pbar = tqdm(dataloader, desc=f"Epoch {epoch}", dynamic_ncols=True, leave=False,
                disable=not is_main)

    for batch in pbar:
        # If any rank gets an empty batch, all ranks skip together; otherwise DDP collectives hang
        if not all_ranks_ok(batch is not None, device):
            continue

        mixture      = batch["mixture"].to(device)       # [B, T]
        enroll       = batch["enroll"].to(device)        # [B, T_e]
        mix_lens     = batch["mix_lens"].to(device)      # [B]
        transcripts  = batch["transcripts"]              # List[str]
        languages    = batch.get("languages", None)      # List[str] or None
        vad_segments = batch.get("vad_segments", None)   # List[Optional[List]]

        optimizer.zero_grad()

        # ── 1. TSE forward ─────────────────────────────────────────────────
        with torch.cuda.amp.autocast(enabled=enable_amp, dtype=amp_dtype or torch.float16):
            tse_out = run_tse_forward(tse_model, mixture, enroll)  # [B, T]

        # ── 2. ASR CE Loss ──────────────────────────────────────────────
        ce_loss     = torch.tensor(0.0, device=device)
        sim_loss    = torch.tensor(0.0, device=device)
        vad_loss    = torch.tensor(0.0, device=device)
        dnsmos_loss = torch.tensor(0.0, device=device)
        sim_tse_enroll_mean = torch.tensor(0.0, device=device)
        sim_mix_enroll_mean = torch.tensor(0.0, device=device)

        if loss_mode in ("ce", "combined"):
            # Use each sample's own language (fixes language bias in mixed zh/en batches)
            ce_loss = asr_model(
                tse_out,
                transcripts,
                language=asr_language,   # fallback language (used when languages is None)
                languages=languages,     # per-sample languages take precedence
            )

        # ── 3. Speaker similarity ranking loss ─────────────────────────────
        # Goal: sim(tse_out, enroll) > sim(mix, enroll) + margin
        # Each sample uses the encoder of its language (spk_encoders)
        if loss_mode in ("similarity", "combined") and spk_loss_fn is not None:
            try:
                sim_loss, sim_tse_enroll_mean, sim_mix_enroll_mean = spk_loss_fn(
                    tse_out, mixture, enroll,
                    languages=languages if languages is not None else ["en"] * tse_out.shape[0],
                )
            except Exception as e:
                logger.warning(f"[Train] speaker similarity loss failed: {e}")
                sim_loss = torch.tensor(0.0, device=device)

        # ── 3.5. Target speaker activity (VAD) loss ────────────────────────
        if loss_mode == "combined" and vad_loss_fn is not None and vad_segments is not None:
            try:
                vad_loss = vad_loss_fn(tse_out, vad_segments, mix_lens, mixture)
            except Exception as e:
                logger.warning(f"[Train] VAD loss failed: {e}")
                vad_loss = torch.tensor(0.0, device=device)

        # ── 3.6. Differentiable DNSMOS loss ────────────────────────────────
        # No reference needed: ref in DNSMOSLoss.forward is interface-only and unused
        if loss_mode == "combined" and dnsmos_loss_fn is not None and lambda_dnsmos > 0:
            try:
                dnsmos_loss = dnsmos_loss_fn(inf=tse_out).mean()
            except Exception as e:
                logger.warning(f"[Train] DNSMOS loss failed: {e}")
                dnsmos_loss = torch.tensor(0.0, device=device)

        # ── 4. Combine losses ──────────────────────────────────────────────
        if loss_mode == "ce":
            loss = lambda_ce * ce_loss
        elif loss_mode == "similarity":
            loss = lambda_sim * sim_loss
        else:  # combined
            loss = (lambda_ce    * ce_loss
                  + lambda_sim   * sim_loss
                  + lambda_vad   * vad_loss
                  + lambda_dnsmos * dnsmos_loss)

        # Same for non-finite losses: if any rank has one, all ranks skip backward
        if not all_ranks_ok(bool(torch.isfinite(loss)), device):
            if is_main:
                logger.warning(f"[Train] step={global_step} loss is not finite, skipping")
            optimizer.zero_grad()
            global_step += 1
            scheduler.step()
            continue

        # ── 5. Backward ────────────────────────────────────────────────────
        if scaler.is_enabled():
            scaler.scale(loss).backward()
            scaler.unscale_(optimizer)
            nn.utils.clip_grad_norm_(tse_model.parameters(), clip_grad)
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            nn.utils.clip_grad_norm_(tse_model.parameters(), clip_grad)
            optimizer.step()

        scheduler.step()
        global_step += 1

        # ── 6. Cross-GPU loss sync (logging only, gradients unaffected) ─────
        loss_t    = reduce_mean(loss.detach())
        ce_t      = reduce_mean(ce_loss.detach() if torch.is_tensor(ce_loss) else
                                torch.tensor(ce_loss, device=device))
        sim_t     = reduce_mean(sim_loss.detach() if torch.is_tensor(sim_loss) else
                                torch.tensor(sim_loss, device=device))
        vad_t     = reduce_mean(vad_loss.detach() if torch.is_tensor(vad_loss) else
                                torch.tensor(vad_loss, device=device))
        dnsmos_t  = reduce_mean(dnsmos_loss.detach() if torch.is_tensor(dnsmos_loss) else
                                torch.tensor(dnsmos_loss, device=device))
        sim_tse_t = reduce_mean(sim_tse_enroll_mean.detach()
                                if torch.is_tensor(sim_tse_enroll_mean) else
                                torch.tensor(sim_tse_enroll_mean, device=device))
        sim_mix_t = reduce_mean(sim_mix_enroll_mean.detach()
                                if torch.is_tensor(sim_mix_enroll_mean) else
                                torch.tensor(sim_mix_enroll_mean, device=device))

        loss_val    = loss_t.item()
        ce_val      = ce_t.item()
        sim_val     = sim_t.item()
        vad_val       = vad_t.item()
        dnsmos_val    = dnsmos_t.item()
        sim_tse_val   = sim_tse_t.item()
        sim_mix_val   = sim_mix_t.item()
        running_loss   += loss_val
        running_ce     += ce_val
        running_sim    += sim_val
        running_vad    += vad_val
        running_dnsmos += dnsmos_val
        n_batches      += 1
        epoch_loss_sum += loss_val
        epoch_batches  += 1

        current_lr = scheduler.get_last_lr()
        if is_main:
            postfix = {"loss": f"{loss_val:.4f}", "lr": f"{current_lr:.2e}"}
            if loss_mode in ("ce", "combined"):
                postfix["ce"] = f"{ce_val:.4f}"
            if loss_mode in ("similarity", "combined"):
                postfix["sim"] = f"{sim_val:.4f}"
            if loss_mode == "combined" and vad_loss_fn is not None:
                postfix["vad"] = f"{vad_val:.4f}"
            if loss_mode == "combined" and dnsmos_loss_fn is not None and lambda_dnsmos > 0:
                postfix["dnsmos_loss"] = f"{dnsmos_val:.4f}"  # negative; closer to 0 is better
            pbar.set_postfix(postfix)

        if global_step % log_every == 0 and is_main:
            avg_loss   = running_loss   / max(n_batches, 1)
            avg_ce     = running_ce     / max(n_batches, 1)
            avg_sim    = running_sim    / max(n_batches, 1)
            avg_vad    = running_vad    / max(n_batches, 1)
            avg_dnsmos = running_dnsmos / max(n_batches, 1)
            log_parts = (
                f"[Train] epoch={epoch} step={global_step} loss={avg_loss:.4f}"
            )
            if loss_mode in ("ce", "combined"):
                log_parts += f" ce={avg_ce:.4f}"
            if loss_mode in ("similarity", "combined"):
                log_parts += (
                    f" sim={avg_sim:.4f}"
                    f" sim_tse={sim_tse_val:.3f}"
                    f" sim_mix={sim_mix_val:.3f}"
                )
            if loss_mode == "combined" and vad_loss_fn is not None:
                log_parts += f" vad={avg_vad:.4f}"
            if loss_mode == "combined" and dnsmos_loss_fn is not None and lambda_dnsmos > 0:
                log_parts += f" dnsmos_loss={avg_dnsmos:.4f}"
            log_parts += f" lr={current_lr:.2e}"
            logger.info(log_parts)
            if writer is not None:
                writer.add_scalar("train/loss",           avg_loss,       global_step)
                writer.add_scalar("train/ce_loss",        avg_ce,         global_step)
                writer.add_scalar("train/sim_loss",       avg_sim,        global_step)
                writer.add_scalar("train/vad_loss",       avg_vad,        global_step)
                writer.add_scalar("train/dnsmos_loss",    avg_dnsmos,     global_step)
                writer.add_scalar("train/sim_tse_enroll", sim_tse_val,    global_step)
                writer.add_scalar("train/sim_mix_enroll", sim_mix_val,    global_step)
                writer.add_scalar("train/lr",             current_lr,     global_step)
            running_loss = running_ce = running_sim = running_vad = running_dnsmos = 0.0
            n_batches = 0

        # ── 7. Periodic checkpoint (rank 0 only) ───────────────────────────
        if global_step % save_step_int == 0 and is_main:
            ckpt_path = model_dir / f"checkpoint_step{global_step:07d}.pt"
            save_checkpoint(
                str(ckpt_path),
                step=global_step,
                epoch=epoch,
                tse_model=raw_model,      # save the raw module, without the DDP wrapper
                optimizer=optimizer,
                scheduler=scheduler,
                best_loss=best_loss,
            )
            latest = model_dir / "latest_checkpoint.pt"
            if latest.is_symlink() or latest.exists():
                latest.unlink()
            latest.symlink_to(ckpt_path.name)
            rotate_checkpoints(str(model_dir), max_keep_ckpts)
            logger.info(f"[Ckpt] saved step={global_step}: {ckpt_path.name}")

    # No valid batches -> inf, so the epoch is never picked as best
    epoch_loss = epoch_loss_sum / epoch_batches if epoch_batches > 0 else float("inf")
    return epoch_loss, global_step


# ===========================================================================
# Config loading
# ===========================================================================

def load_config(config_path: str, overrides: Optional[Dict] = None) -> Dict:
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    if overrides:
        cfg.update(overrides)
    return cfg


def resolve_path(path: str, base: Path) -> str:
    """Resolve a path relative to the script directory to an absolute path"""
    p = Path(path)
    if not p.is_absolute():
        p = (base / p).resolve()
    return str(p)


_AMP_DTYPES: Dict[str, Optional[torch.dtype]] = {
    "bfloat16": torch.bfloat16, "bf16": torch.bfloat16,
    "float16": torch.float16, "fp16": torch.float16, "half": torch.float16,
    "float32": None, "fp32": None, "float": None,
}


def parse_amp_dtype(name) -> Optional[torch.dtype]:
    """amp_dtype config value -> autocast dtype (None = full float32, AMP off)."""
    key = str(name).strip().lower()
    if key not in _AMP_DTYPES:
        raise ValueError(
            f"invalid amp_dtype={name!r}; use one of: bfloat16/bf16, float16/fp16, float32/fp32"
        )
    return _AMP_DTYPES[key]


def setup_logging(exp_dir: str) -> logging.Logger:
    log_dir = Path(exp_dir)
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / "train.log"

    fmt = "%(asctime)s [%(levelname)s] %(message)s"
    logging.basicConfig(
        level=logging.INFO,
        format=fmt,
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler(str(log_path), mode="a"),
        ],
    )
    return logging.getLogger("tse_asr_train")


# ===========================================================================
# Background evaluation after each epoch
# ===========================================================================

def launch_async_epoch_eval(
    epoch: int,
    exp_dir: str,
    logger: logging.Logger,
    state: Optional[Dict] = None,
    cfg: Optional[Dict] = None,
) -> Dict:
    """
    Launch a full REAL-T evaluation in the background after each epoch.

    Behaviour:
        - intended to be called on rank 0 only
        - by default, skips this epoch if the previous evaluation is still running
        - after evaluation, copies the *_summary.txt from the output directory to
            <exp_dir>/eval_summaries/, archived per epoch so later runs don't overwrite it
    """
    state = dict(state or {})
    cfg = cfg or {}

    enabled = cfg.get("epoch_eval_enabled", True)
    if not enabled:
        return state

    prev_proc = state.get("proc")
    skip_if_running = cfg.get("epoch_eval_skip_if_running", True)
    if prev_proc is not None and prev_proc.poll() is None:
        prev_epoch = state.get("epoch")
        prev_log = state.get("log_path")
        if skip_if_running:
            logger.info(
                f"[Eval] skipping epoch={epoch}: previous background evaluation still running "
                f"(epoch={prev_epoch}, pid={prev_proc.pid}, log={prev_log})"
            )
            return state

    exp_dir_path = Path(exp_dir).resolve()
    real_t_root = (_SCRIPT_DIR.parent / "REAL-TSE-Challenge").resolve()
    output_root = Path(
        cfg.get("epoch_eval_output_root", str(real_t_root / "output"))
    ).resolve()
    test_set = str(cfg.get("epoch_eval_test_set", "DEV")).upper()
    cuda_id = str(cfg.get("epoch_eval_cuda", "2"))
    fast_flag = bool(cfg.get("epoch_eval_fast", True))

    model_label = exp_dir_path.name
    output_dir = output_root / test_set / model_label
    eval_logs_dir = exp_dir_path / "eval_logs"
    eval_summaries_dir = exp_dir_path / "eval_summaries"
    eval_logs_dir.mkdir(parents=True, exist_ok=True)
    eval_summaries_dir.mkdir(parents=True, exist_ok=True)

    log_path = eval_logs_dir / f"eval_epoch{epoch:03d}.log"
    fast_arg = "--fast " if fast_flag else ""

    cmd = f"""set -euo pipefail
cd {shlex.quote(str(real_t_root))}
bash ./run_all_eval.sh {fast_arg}--model {shlex.quote(str(exp_dir_path))} --test-set {shlex.quote(test_set)} --cuda {shlex.quote(cuda_id)}
summary_file=$(find {shlex.quote(str(output_dir))} -maxdepth 1 -type f -name '*_summary.txt' | sort | head -n 1 || true)
if [ -n "$summary_file" ] && [ -f "$summary_file" ]; then
    summary_base=$(basename "$summary_file")
    cp "$summary_file" {shlex.quote(str(eval_summaries_dir))}/epoch_{epoch:03d}_${{summary_base}}
fi
"""

    with open(log_path, "a", encoding="utf-8") as log_f:
        log_f.write(
            f"\n========== epoch {epoch} eval start: {datetime.datetime.now():%Y-%m-%d %H:%M:%S} =========="
            f"\nmodel={exp_dir_path}\ntest_set={test_set}\ncuda={cuda_id}\noutput_dir={output_dir}\n\n"
        )

    proc = subprocess.Popen(
        ["bash", "-lc", cmd],
        stdout=open(log_path, "a", encoding="utf-8"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    logger.info(
        f"[Eval] started background evaluation for epoch={epoch}, pid={proc.pid}, "
        f"output_dir={output_dir}, log={log_path}"
    )
    logger.info(
        f"[Eval] the summary will be archived to: {eval_summaries_dir}"
    )
    return {
        "proc": proc,
        "epoch": epoch,
        "log_path": str(log_path),
        "output_dir": str(output_dir),
        "summary_dir": str(eval_summaries_dir),
    }


# ===========================================================================
# DDP utilities
# ===========================================================================

def is_dist_avail_and_initialized() -> bool:
    return dist.is_available() and dist.is_initialized()


def get_rank() -> int:
    if not is_dist_avail_and_initialized():
        return 0
    return dist.get_rank()


def get_world_size() -> int:
    if not is_dist_avail_and_initialized():
        return 1
    return dist.get_world_size()


def is_main_process() -> bool:
    return get_rank() == 0


def setup_ddp():
    """
    Initialize DDP. torchrun sets the RANK / LOCAL_RANK / WORLD_SIZE environment variables.
    Does nothing on a single GPU.
    """
    if "LOCAL_RANK" not in os.environ:
        return  # single-GPU mode, nothing to initialize

    local_rank = int(os.environ["LOCAL_RANK"])
    torch.cuda.set_device(local_rank)
    dist.init_process_group(backend="nccl")


def cleanup_ddp():
    if is_dist_avail_and_initialized():
        dist.destroy_process_group()


def reduce_mean(tensor: torch.Tensor) -> torch.Tensor:
    """All-reduce mean across GPUs (no-op on a single GPU)"""
    if not is_dist_avail_and_initialized():
        return tensor
    t = tensor.clone()
    dist.all_reduce(t, op=dist.ReduceOp.SUM)
    t /= get_world_size()
    return t


def all_ranks_ok(ok: bool, device: torch.device) -> bool:
    """True only if ok is True on every rank (keeps DDP ranks skipping in lockstep)"""
    if not is_dist_avail_and_initialized():
        return ok
    t = torch.tensor(0 if ok else 1, dtype=torch.int32, device=device)
    dist.all_reduce(t, op=dist.ReduceOp.MAX)
    return t.item() == 0


# ===========================================================================
# Entry point
# ===========================================================================

def resolve_spk_encoder_paths(cfg: Dict) -> Dict[str, str]:
    """
    Language -> speaker encoder directory.
    New style:    spk_encoders: {en: ..., zh: ..., th: ...}
    Legacy keys:  spk_encoder_en_path / spk_encoder_chs_path (still honored;
                  spk_encoders entries take precedence).
    """
    paths: Dict[str, str] = {}
    if cfg.get("spk_encoder_en_path"):
        paths["en"] = cfg["spk_encoder_en_path"]
    if cfg.get("spk_encoder_chs_path"):
        paths["zh"] = cfg["spk_encoder_chs_path"]
    for lang, path in (cfg.get("spk_encoders") or {}).items():
        if path:
            paths[normalize_lang(lang)] = path
    if not paths:
        # Original author's defaults
        paths = {
            "en": "/home/yuque3/nwy/real-t/spk_emb_models/voxceleb_resnet34_LM",
            "zh": "/home/yuque3/nwy/real-t/spk_emb_models/cnceleb_resnet34_LM",
        }
    return {lang: resolve_path(p, _SCRIPT_DIR) for lang, p in paths.items()}


def main():
    parser = argparse.ArgumentParser(description="TSE-ASR end-to-end training (single GPU / multi-GPU DDP)")
    parser.add_argument(
        "--config", "-c",
        type=str, required=True,
        help="Training config file (YAML)",
    )
    parser.add_argument(
        "--resume",
        type=str, default=None,
        help="Resume training from this checkpoint (overrides resume in the config)",
    )
    parser.add_argument(
        "--exp_dir",
        type=str, default=None,
        help="Experiment directory (overrides exp_dir in the config)",
    )
    parser.add_argument(
        "--pretrained_tse",
        type=str, default=None,
        help="Initialize model weights only from this checkpoint (overrides pretrained_tse in config; optimizer/step/epoch are not restored)",
    )
    parser.add_argument(
        "--max_samples",
        type=int, default=None,
        help="Maximum number of training samples (overrides the config)",
    )
    args = parser.parse_args()

    # ── DDP init ──────────────────────────────────────────────────────────
    setup_ddp()
    rank       = get_rank()
    world_size = get_world_size()
    local_rank = int(os.environ.get("LOCAL_RANK", 0))
    is_main    = is_main_process()

    # ── Load config ───────────────────────────────────────────────────────
    cfg = load_config(args.config)

    # Command-line overrides
    if args.resume      is not None: cfg["resume"]               = args.resume
    if args.exp_dir     is not None: cfg["exp_dir"]              = args.exp_dir
    if args.pretrained_tse is not None: cfg["pretrained_tse"]    = args.pretrained_tse
    if args.max_samples is not None: cfg["data"]["max_samples"]  = args.max_samples

    # Timestamped experiment dir (rank 0 creates the timestamp and broadcasts it to all ranks)
    exp_dir_raw = cfg.get("exp_dir", "exp/tse_asr")
    exp_dir_abs = resolve_path(exp_dir_raw, _SCRIPT_DIR)
    # Check whether the dir name already has a timestamp prefix (YYYYMMDD_HHMMSS_...)
    _name = Path(exp_dir_abs).name
    _parts = _name.split("_")
    _already_timestamped = (
        len(_parts) >= 2
        and len(_parts[0]) == 8 and _parts[0].isdigit()
        and len(_parts[1]) == 6 and _parts[1].isdigit()
    )
    if not _already_timestamped:
        if is_main:
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            # Use the config's exp_dir name as the model tag (e.g. bsrnn_ecapa_vox1)
            model_tag = Path(exp_dir_raw).name
            exp_dir_abs = str(Path(exp_dir_abs).parent / f"{ts}_{model_tag}")
        # Broadcast the exp_dir string to all ranks
        if world_size > 1:
            buf = [exp_dir_abs]
            dist.broadcast_object_list(buf, src=0)
            exp_dir_abs = buf[0]
    cfg["exp_dir"] = exp_dir_abs

    # Only rank 0 creates directories
    model_dir = Path(exp_dir_abs) / "models"
    tb_dir    = Path(exp_dir_abs) / "tensorboard"
    if is_main:
        model_dir.mkdir(parents=True, exist_ok=True)
        tb_dir.mkdir(parents=True, exist_ok=True)
    if world_size > 1:
        dist.barrier()

    # ── Logging (rank 0 writes the log file; other ranks log to stdout) ──
    logger = setup_logging(exp_dir_abs) if is_main else logging.getLogger("tse_asr_train")
    if not is_main:
        logging.basicConfig(level=logging.WARNING)

    # TensorBoard on rank 0 only
    writer = SummaryWriter(log_dir=str(tb_dir)) if is_main else None

    amp_dtype = parse_amp_dtype(cfg.get("amp_dtype", "float32"))   # fail fast on typos
    if is_main:
        logger.info(f"Experiment dir: {exp_dir_abs}")
        if cfg.get("enable_amp", False) and amp_dtype is None:
            logger.warning("enable_amp is true but amp_dtype is float32; training in full float32")
        logger.info(
            f"Precision: "
            f"{amp_dtype if cfg.get('enable_amp', False) and amp_dtype is not None else 'float32 (AMP off)'}"
        )
        logger.info(f"Config file: {args.config}")
        logger.info(f"Distributed training: world_size={world_size}")

        config_save_path = Path(exp_dir_abs) / "config.yaml"
        if not config_save_path.exists():
            shutil.copy(args.config, str(config_save_path))

    # ── Random seed (offset by rank) ──────────────────────────────────────
    seed = cfg.get("seed", 42) + rank
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # ── Device ────────────────────────────────────────────────────────────
    if torch.cuda.is_available():
        device = torch.device(f"cuda:{local_rank}")
    else:
        device = torch.device("cpu")
    if is_main:
        logger.info(f"rank={rank} device: {device}, world_size={world_size}")

    # ── Dataset ───────────────────────────────────────────────────────────
    data_cfg = cfg["data"]

    # Training data roots; accepted forms:
    #   train_roots: [path1, path2, ...]   → multiple roots (new style)
    #   train_root: path                   → single root (old style, still supported)
    #   if both are set, train_roots wins
    _roots_raw = data_cfg.get("train_roots", None)
    if _roots_raw is None:
        # Backward compatibility with the old train_root (single string)
        _root_single = data_cfg.get("train_root", None)
        if _root_single is None:
            raise ValueError("[Data] the config must set train_roots or train_root")
        _roots_raw = [_root_single]
    elif isinstance(_roots_raw, str):
        _roots_raw = [_roots_raw]

    train_roots = [resolve_path(r, _SCRIPT_DIR) for r in _roots_raw]
    if is_main:
        logger.info(f"[Data] training data roots: {train_roots}")

    train_dataset = TSEASRDataset(
        train_roots        = train_roots,
        datasets           = data_cfg.get("datasets", ["CHiME6", "AMI", "AliMeeting", "AISHELL-4"]),
        dataset_subdirs    = data_cfg,
        sample_rate        = data_cfg.get("sample_rate", 16000),
        max_mix_len        = data_cfg.get("max_mix_len", 480000),
        max_enroll_len     = data_cfg.get("max_enroll_len", 160000),
        min_transcript_len = data_cfg.get("min_transcript_len", 2),
        max_samples        = data_cfg.get("max_samples", 0),
        peak_normalize     = data_cfg.get("peak_normalize", True),
    )
    if len(train_dataset) == 0:
        raise ValueError(
            f"[Data] no training samples found under train_roots={train_roots} for datasets="
            f"{data_cfg.get('datasets')}; check data.train_roots in {args.config} "
            f"(the warnings above list the missing files)"
        )

    # DDP: DistributedSampler replaces shuffle=True
    sampler = (
        DistributedSampler(train_dataset, num_replicas=world_size, rank=rank, shuffle=True)
        if world_size > 1
        else None
    )
    dataloader = DataLoader(
        train_dataset,
        batch_size  = cfg.get("batch_size", 1),
        shuffle     = (sampler is None),   # shuffle on a single GPU; the sampler handles it on multiple GPUs
        sampler     = sampler,
        num_workers = cfg.get("num_workers", 4),
        collate_fn  = tse_asr_collate_fn,
        drop_last   = False,
        pin_memory  = True,
    )
    if is_main:
        logger.info(f"DataLoader: {len(train_dataset)} samples, {len(dataloader)} batches/epoch/rank")

    # ── TSE model ─────────────────────────────────────────────────────────
    _DEFAULT_TSE = "/home/yuque3/nwy/real-t/REAL-TSE-Challenge/pretrained/bsrnn_ecapa_vox1/avg_model.pt"
    pretrained_tse = cfg.get("pretrained_tse", _DEFAULT_TSE) or _DEFAULT_TSE
    if pretrained_tse and not os.path.isabs(pretrained_tse):
        pretrained_tse = resolve_path(pretrained_tse, _SCRIPT_DIR)

    tse_model = build_tse_model(cfg, pretrained_path=pretrained_tse)
    tse_model = tse_model.to(device)

    # Multi-GPU: wrap in DDP
    if world_size > 1:
        tse_model = torch.nn.parallel.DistributedDataParallel(
            tse_model,
            device_ids=[local_rank],
            output_device=local_rank,
            find_unused_parameters=cfg.get("find_unused_parameters", False),
        )

    if is_main:
        _m = tse_model.module if world_size > 1 else tse_model
        n_params = sum(p.numel() for p in _m.parameters())
        n_train  = sum(p.numel() for p in _m.parameters() if p.requires_grad)
        logger.info(f"TSE model parameters: total={n_params/1e6:.2f}M, trainable={n_train/1e6:.2f}M")

    # ── Resolve loss_mode (decided once, here in main) ────────────────────
    loss_mode = cfg.get("loss_mode", "combined")
    # Backward compatibility with the old lambda_spk
    if cfg.get("lambda_spk", 0.0) > 0 and loss_mode == "ce":
        loss_mode = "combined"
    valid_modes = ("ce", "similarity", "combined")
    if loss_mode not in valid_modes:
        raise ValueError(f"invalid loss_mode={loss_mode!r}, valid values: {valid_modes}")
    if is_main:
        logger.info(f"[Loss] loss_mode={loss_mode}")

    # ── ASR model (frozen Whisper; loaded only for ce / combined) ─────────
    asr_model = None
    if loss_mode in ("ce", "combined"):
        _DEFAULT_WHISPER = "/home/yuque3/nwy/models/whisper-large-v3"
        whisper_path = cfg.get("whisper_model_path", _DEFAULT_WHISPER) or _DEFAULT_WHISPER
        if not os.path.isabs(whisper_path):
            whisper_path = resolve_path(whisper_path, _SCRIPT_DIR)
        asr_model = FrozenWhisperASR(whisper_path, device=str(device))
        asr_model = asr_model.to(device)
        asr_model.check_languages(train_dataset.languages())
        if is_main:
            logger.info(f"[ASR] Whisper loaded: {whisper_path}")
    else:
        if is_main:
            logger.info("[ASR] loss_mode=similarity, not loading Whisper")

    # ── Speaker similarity loss (loaded only for similarity / combined) ──
    # One encoder per language, matching the evaluation side
    spk_loss_fn = None
    if loss_mode in ("similarity", "combined"):
        encoder_paths = resolve_spk_encoder_paths(cfg)
        missing = [l for l in train_dataset.languages() if l not in encoder_paths]
        if missing:
            raise ValueError(
                f"[Loss] training data has languages {missing} without a speaker encoder; "
                f"add them under spk_encoders in the config (configured: {sorted(encoder_paths)})"
            )
        margin = cfg.get("sim_margin", 0.2)
        by_path: Dict[str, FrozenSpeakerEncoder] = {}   # languages sharing a model share one instance
        encoders: Dict[str, FrozenSpeakerEncoder] = {}
        for lang, path in encoder_paths.items():
            if path not in by_path:
                by_path[path] = FrozenSpeakerEncoder(path, device=str(device)).to(device)
            encoders[lang] = by_path[path]
        spk_loss_fn = SpeakerSimilarityLoss(encoders=encoders, margin=margin)
        if is_main:
            logger.info(
                f"[Loss] speaker similarity ranking loss enabled: margin={margin}, encoders="
                + ", ".join(f"{l}={p}" for l, p in encoder_paths.items())
            )

    # ── Target speaker VAD loss (combined mode with lambda_vad > 0) ──────
    vad_loss_fn = None
    lambda_vad = cfg.get("lambda_vad", 0.5)
    if loss_mode == "combined" and lambda_vad > 0:
        vad_frame_shift_ms  = cfg.get("vad_frame_shift_ms", 10.0)
        vad_frame_length_ms = cfg.get("vad_frame_length_ms", 25.0)
        vad_loss_fn = TargetVADLoss(
            sample_rate=data_cfg.get("sample_rate", 16000),
            frame_shift_ms=vad_frame_shift_ms,
            frame_length_ms=vad_frame_length_ms,
            threshold_db=cfg.get("vad_threshold_db", -40.0),
            slope_db=cfg.get("vad_slope_db", 5.0),
        )
        if is_main:
            logger.info(
                f"[Loss] target speaker VAD loss enabled: "
                f"lambda_vad={lambda_vad}, "
                f"frame_shift={vad_frame_shift_ms}ms, "
                f"frame_length={vad_frame_length_ms}ms, "
                f"threshold={vad_loss_fn.threshold_db}dB, slope={vad_loss_fn.slope_db}dB"
            )

    # ── Differentiable DNSMOS loss (combined mode with lambda_dnsmos > 0) ─
    dnsmos_loss_fn = None
    lambda_dnsmos = cfg.get("lambda_dnsmos", 0.0)
    if loss_mode == "combined" and lambda_dnsmos > 0:
        if not _DNSMOS_LOSS_AVAILABLE:
            logger.warning(
                "[Loss] DNSMOSLoss is unavailable, skipping the DNSMOS loss."
            )
        else:
            import os as _os
            _dnsmos_dir = cfg.get("dnsmos_model_dir", None) or \
                          _os.environ.get("DNSMOS_MODEL_DIR", None) or \
                          str(_SCRIPT_DIR.parent / "REAL-TSE-Challenge" / "DNSMOS")
            _primary = str(Path(_dnsmos_dir) / "sig_bak_ovr.pt")
            _p808    = str(Path(_dnsmos_dir) / "model_v8.pt")
            _target  = cfg.get("dnsmos_target", "OVRL")
            try:
                dnsmos_loss_fn = DNSMOSLoss(
                    primary_model_path=_primary,
                    p808_model_path=_p808,
                    target_metric=_target,
                )
                dnsmos_loss_fn = dnsmos_loss_fn.to(device)
                if is_main:
                    logger.info(
                        f"[Loss] differentiable DNSMOS loss enabled: "
                        f"target={_target}, lambda_dnsmos={lambda_dnsmos}, "
                        f"model_dir={_dnsmos_dir}"
                    )
            except Exception as e:
                logger.warning(f"[Loss] DNSMOSLoss initialization failed, skipping: {e}")
                dnsmos_loss_fn = None

    # ── Optimizer ─────────────────────────────────────────────────────────
    opt_cfg = cfg.get("optimizer", {"lr": 1e-5, "weight_decay": 1e-5})
    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, tse_model.parameters()),
        lr           = opt_cfg.get("lr", 1e-5),
        weight_decay = opt_cfg.get("weight_decay", 1e-5),
    )
    if is_main:
        logger.info(f"Optimizer: AdamW, lr={opt_cfg.get('lr', 1e-5):.1e}")

    # ── Learning-rate scheduler ───────────────────────────────────────────
    sch_cfg    = cfg.get("scheduler_args", {})
    num_epochs = cfg.get("num_epochs", 50)
    epoch_iter = max(len(dataloader), 1)

    scheduler = ExponentialDecayScheduler(
        optimizer      = optimizer,
        initial_lr     = sch_cfg.get("initial_lr", opt_cfg.get("lr", 1e-5)),
        final_lr       = sch_cfg.get("final_lr", 1e-6),
        num_epochs     = num_epochs,
        epoch_iter     = epoch_iter,
        warm_up_epoch  = sch_cfg.get("warm_up_epoch", 1),
        warm_from_zero = sch_cfg.get("warm_from_zero", False),
    )
    if is_main:
        logger.info(
            f"Scheduler: ExponentialDecay, "
            f"lr: {sch_cfg.get('initial_lr', 1e-5):.1e} -> {sch_cfg.get('final_lr', 1e-6):.1e}"
        )

    # ── Resume ────────────────────────────────────────────────────────────
    start_epoch = 1
    global_step = 0
    best_loss   = float("inf")

    resume_path = cfg.get("resume", None)
    if resume_path and resume_path != "null":
        resume_path = resolve_path(resume_path, _SCRIPT_DIR)
        # Unwrapped module (before DDP)
        raw_model = tse_model.module if world_size > 1 else tse_model
        global_step, saved_epoch, best_loss, epoch_finished = load_checkpoint(
            resume_path, raw_model, optimizer, scheduler
        )
        start_epoch = resolve_resume_epoch(saved_epoch, epoch_finished)

    cfg["_best_loss"] = best_loss
    eval_state: Dict = {}
    if is_main:
        logger.info(f"Starting training: epoch={start_epoch}..{num_epochs}, step={global_step}, world_size={world_size}")
        logger.info(
            "[Eval] per-epoch background evaluation enabled: "
            f"test_set={str(cfg.get('epoch_eval_test_set', 'DEV')).upper()}, "
            f"cuda={cfg.get('epoch_eval_cuda', '2')}, "
            f"fast={bool(cfg.get('epoch_eval_fast', True))}, "
            f"skip_if_running={bool(cfg.get('epoch_eval_skip_if_running', True))}"
        )

    # ── Training loop ─────────────────────────────────────────────────────
    for epoch in range(start_epoch, num_epochs + 1):
        # DDP: set the sampler epoch so each epoch is shuffled differently
        if sampler is not None:
            sampler.set_epoch(epoch)

        epoch_start = time.time()

        epoch_loss, global_step = train_one_epoch(
            tse_model   = tse_model,
            asr_model   = asr_model,
            dataloader  = dataloader,
            optimizer   = optimizer,
            scheduler   = scheduler,
            device      = device,
            epoch       = epoch,
            global_step = global_step,
            cfg         = cfg,
            writer      = writer if is_main else None,
            logger      = logger,
            spk_loss_fn    = spk_loss_fn,
            vad_loss_fn    = vad_loss_fn,
            dnsmos_loss_fn = dnsmos_loss_fn,
            is_main        = is_main,
            world_size  = world_size,
        )

        elapsed = time.time() - epoch_start

        if is_main:
            logger.info(
                f"[Epoch {epoch}/{num_epochs}] loss={epoch_loss:.4f} "
                f"step={global_step} time={elapsed/60:.1f}min"
            )
            if writer is not None:
                writer.add_scalar("train/epoch_loss", epoch_loss, epoch)

            # Save the best model (rank 0 only, using the module's state_dict)
            raw_model = tse_model.module if world_size > 1 else tse_model
            if epoch_loss < best_loss:
                best_loss = epoch_loss
                cfg["_best_loss"] = best_loss
                best_path = model_dir / "best_checkpoint.pt"
                save_checkpoint(
                    str(best_path),
                    step=global_step,
                    epoch=epoch,
                    tse_model=raw_model,
                    optimizer=optimizer,
                    scheduler=scheduler,
                    best_loss=best_loss,
                    epoch_finished=True,
                )
                logger.info(f"[Best] epoch={epoch} loss={best_loss:.4f} -> {best_path.name}")

            save_checkpoint(
                model_dir / f"checkpoint_epoch{epoch:03d}.pt",
                step=global_step,
                epoch=epoch,
                tse_model=raw_model,
                optimizer=optimizer,
                scheduler=scheduler,
                best_loss=best_loss,
                epoch_finished=True,
            )
            eval_state = launch_async_epoch_eval(
                epoch=epoch,
                exp_dir=exp_dir_abs,
                logger=logger,
                state=eval_state,
                cfg=cfg,
            )
        
        # Sync all ranks (so slow ranks don't race checkpoint writing)
        if world_size > 1:
            dist.barrier()

    if writer is not None:
        writer.close()
    if is_main:
        logger.info("Training finished!")

    cleanup_ddp()


if __name__ == "__main__":
    main()
